# Generated by Django 5.2.1 on 2025-05-20 10:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="path",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
