# Generated by Django 5.2.1 on 2025-05-20 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_track_path"),
    ]

    operations = [
        # migrations.RunSQL(
        #     "CREATE INDEX point_track_id_idx ON maps_point (track_id);",
        #     reverse_sql="DROP INDEX point_track_id_idx ON maps_point;",
        # ),
        # migrations.RunSQL(
        #     "CREATE INDEX point_datetime_idx ON maps_point (datetime);",
        #     reverse_sql="DROP INDEX point_datetime_idx ON maps_point;",
        # ),
    ]
