# Generated by Django 2.1 on 2018-09-04 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_trip_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={"ordering": ["date"]},
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="start_data",
            new_name="start_date",
        ),
    ]
