# Generated by Django 5.2.1 on 2025-05-23 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0003_add_point_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="track",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.DeleteModel(
            name="Point",
        ),
    ]
