# Generated by Django 2.1 on 2018-09-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20180904_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='blog',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='blog_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
