# Generated by Django 5.2.1 on 2025-06-06 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0004_remove_point_track_delete_note_delete_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="blog",
        ),
    ]
