# Generated by Django 2.1 on 2018-09-11 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0004_auto_20180905_1730"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="statistic",
            old_name="ascend",
            new_name="ascent",
        ),
        migrations.RenameField(
            model_name="statistic",
            old_name="descend",
            new_name="descent",
        ),
    ]
