# Generated by Django 5.2.1 on 2025-06-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_remove_trip_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='blog_category',
            field=models.SmallIntegerField(),
        ),
    ]
