# Generated by Django 2.1.3 on 2018-11-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_commentqty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentqty',
            unique_together={('post_id', 'trip')},
        ),
    ]
